# Generated by Django 2.2.3 on 2019-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190727_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
